name: e_commerce_app_c9_mon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  flutter_image_slider: ^0.0.2
  lottie: ^2.6.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: Poppines
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
